# -*- coding: utf-8 -*-
"""Phase 0 patch — ตัดฟีเจอร์ตาย + แก้บั๊ก safe_json_parse

หมายเหตุ: สคริปต์นี้รันไปแล้วครั้งเดียวตอนสร้าง trend_final_v2.py (ตอนนั้นยังอยู่ที่
workspace/phase0_cleanup/trend_final.py) - เก็บไว้เป็นบันทึกว่าแก้อะไรไปบ้าง ไม่ต้องรันซ้ำ
เว้นแต่จะสร้าง trend_final_v2.py ใหม่จาก trend_final.py (root) อีกครั้ง"""
import io

P = r"D:\Users\keingkrai_b\Desktop\Trend\trend_final_v2.py"
s = io.open(P, encoding="utf-8").read()
orig = s
edits = []


def rep(label, old, new):
    global s
    assert old in s, "NOT FOUND: " + label
    s = s.replace(old, new, 1)
    edits.append(label)


# ── A. แก้บั๊ก safe_json_parse — ลอง json.loads() ตรงๆ ก่อนเสมอ ──────────────
A_OLD = (
    "    content = content.strip()\n"
    "\n"
    "    # 1\ufe0f\u20e3 FIX: Remove over-escaped quotes generated by smaller models like Llama 3\n"
    "    content = content.replace('\\\\\"', '\"')"
)
A_NEW = (
    "    content = content.strip()\n"
    "\n"
    "    # 0\ufe0f\u20e3 FIX (Phase 0, 2026-08-28): \u0e25\u0e2d\u0e07 parse \u0e15\u0e23\u0e07\u0e46 \u0e01\u0e48\u0e2d\u0e19\u0e40\u0e2a\u0e21\u0e2d\n"
    "    # \u0e40\u0e14\u0e34\u0e21\u0e42\u0e04\u0e49\u0e14\u0e01\u0e23\u0e30\u0e42\u0e14\u0e14\u0e44\u0e1b\u0e17\u0e33 .replace() \u0e17\u0e31\u0e19\u0e17\u0e35\u0e42\u0e14\u0e22\u0e44\u0e21\u0e48\u0e25\u0e2d\u0e07\u0e01\u0e48\u0e2d\u0e19 \u0e0b\u0e36\u0e48\u0e07\u0e15\u0e31\u0e49\u0e07\u0e43\u0e08\u0e41\u0e01\u0e49\u0e1b\u0e31\u0e0d\u0e2b\u0e32\u0e42\u0e21\u0e40\u0e14\u0e25\u0e40\u0e25\u0e47\u0e01\n"
    "    # (Llama 3) \u0e17\u0e35\u0e48 over-escape \u0e41\u0e15\u0e48\u0e21\u0e31\u0e19\u0e44\u0e1b\u0e17\u0e33\u0e25\u0e32\u0e22 escaped quote \u0e17\u0e35\u0e48\u0e16\u0e39\u0e01\u0e15\u0e49\u0e2d\u0e07\u0e2d\u0e22\u0e39\u0e48\u0e41\u0e25\u0e49\u0e27\u0e14\u0e49\u0e27\u0e22\n"
    "    # \u0e40\u0e0a\u0e48\u0e19\u0e40\u0e27\u0e25\u0e32 LLM \u0e15\u0e2d\u0e1a\u0e04\u0e33\u0e17\u0e35\u0e48\u0e21\u0e35\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e2b\u0e21\u0e32\u0e22\u0e04\u0e33\u0e1e\u0e39\u0e14\u0e0b\u0e49\u0e2d\u0e19\u0e43\u0e19\u0e04\u0e48\u0e32 string \u0e0b\u0e36\u0e48\u0e07\u0e16\u0e39\u0e01\u0e15\u0e32\u0e21\u0e2b\u0e25\u0e31\u0e01 JSON \u0e17\u0e38\u0e01\u0e1b\u0e23\u0e30\u0e01\u0e32\u0e23 \u0e01\u0e25\u0e31\u0e1a\u0e1e\u0e31\u0e07\n"
    "    # \u0e17\u0e31\u0e19\u0e17\u0e35 - \u0e40\u0e08\u0e2d\u0e08\u0e23\u0e34\u0e07\u0e15\u0e2d\u0e19\u0e23\u0e31\u0e19 pilot \u0e2d\u0e35\u0e04\u0e2d\u0e21\u0e40\u0e21\u0e34\u0e23\u0e4c\u0e0b\u0e15\u0e48\u0e32\u0e07\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28 (2026-08-27) \u0e17\u0e33\u0e43\u0e2b\u0e49\u0e2a\u0e23\u0e38\u0e1b\u0e1c\u0e25\u0e2b\u0e32\u0e22\u0e17\u0e31\u0e49\u0e07\u0e23\u0e2d\u0e1a\n"
    "    # \u0e17\u0e32\u0e07\u0e41\u0e01\u0e49: JSON \u0e17\u0e35\u0e48\u0e16\u0e39\u0e01\u0e2d\u0e22\u0e39\u0e48\u0e41\u0e25\u0e49\u0e27\u0e15\u0e49\u0e2d\u0e07\u0e1c\u0e48\u0e32\u0e19\u0e15\u0e31\u0e49\u0e07\u0e41\u0e15\u0e48\u0e14\u0e48\u0e32\u0e19\u0e41\u0e23\u0e01 \u0e2a\u0e48\u0e27\u0e19\u0e15\u0e31\u0e27\u0e0b\u0e48\u0e2d\u0e21\u0e14\u0e49\u0e32\u0e19\u0e25\u0e48\u0e32\u0e07\u0e40\u0e01\u0e47\u0e1a\u0e44\u0e27\u0e49\u0e40\u0e1b\u0e47\u0e19 fallback\n"
    "    # \u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e01\u0e23\u0e13\u0e35 over-escape \u0e08\u0e23\u0e34\u0e07\u0e40\u0e2b\u0e21\u0e37\u0e2d\u0e19\u0e40\u0e14\u0e34\u0e21 \u0e44\u0e21\u0e48\u0e44\u0e14\u0e49\u0e25\u0e14\u0e04\u0e27\u0e32\u0e21\u0e2a\u0e32\u0e21\u0e32\u0e23\u0e16\u0e40\u0e14\u0e34\u0e21\u0e25\u0e07\u0e40\u0e25\u0e22\n"
    "    try:\n"
    "        return json.loads(content)\n"
    "    except Exception:\n"
    "        pass\n"
    "\n"
    "    # 1\ufe0f\u20e3 FIX: Remove over-escaped quotes generated by smaller models like Llama 3\n"
    "    content = content.replace('\\\\\"', '\"')"
)
rep("A. safe_json_parse: \u0e25\u0e2d\u0e07 parse \u0e15\u0e23\u0e07\u0e46 \u0e01\u0e48\u0e2d\u0e19", A_OLD, A_NEW)

# ── B. ตัดฟีเจอร์ตายออกจาก feature_cols ─────────────────────────────────────
rep(
    "B. feature_cols: \u0e15\u0e31\u0e14 2 \u0e1f\u0e35\u0e40\u0e08\u0e2d\u0e23\u0e4c\u0e15\u0e32\u0e22",
    "    feature_cols = ['lag_1', 'lag_3', 'lag_12', 'rolling_mean_3m', 'z_volatility_3m', 'z_velocity', 'news_relevance_count', 'news_momentum']",
    "    # Phase 0 (2026-08-28): \u0e15\u0e31\u0e14 'news_relevance_count', 'news_momentum' \u0e2d\u0e2d\u0e01\n"
    "    # feature importance = 0.0000 \u0e40\u0e1b\u0e4a\u0e30\u0e17\u0e31\u0e49\u0e07 RandomForest \u0e41\u0e25\u0e30 XGBoost \u0e17\u0e38\u0e01 cutoff (\u0e14\u0e39\n"
    "    # Detail/_data/feature_importance_noarima.csv) \u0e41\u0e15\u0e48\u0e40\u0e1b\u0e47\u0e19\u0e15\u0e49\u0e19\u0e17\u0e38\u0e19\u0e43\u0e2b\u0e0d\u0e48\u0e2a\u0e38\u0e14\u0e43\u0e19 pipeline\n"
    "    # \u0e40\u0e1e\u0e23\u0e32\u0e30\u0e15\u0e49\u0e2d\u0e07\u0e22\u0e34\u0e07 Google News + LLM 1 \u0e04\u0e23\u0e31\u0e49\u0e07\u0e15\u0e48\u0e2d\u0e17\u0e38\u0e01\u0e04\u0e39\u0e48 (\u0e04\u0e25\u0e31\u0e2a\u0e40\u0e15\u0e2d\u0e23\u0e4c x \u0e40\u0e14\u0e37\u0e2d\u0e19) \u0e2b\u0e25\u0e32\u0e22\u0e23\u0e49\u0e2d\u0e22\u0e04\u0e39\u0e48\u0e15\u0e48\u0e2d\u0e23\u0e2d\u0e1a\n"
    "    feature_cols = ['lag_1', 'lag_3', 'lag_12', 'rolling_mean_3m', 'z_volatility_3m', 'z_velocity']",
)

# ── C. ตัดออกจาก recursive forecast ────────────────────────────────────────
rep(
    "C. recursive forecast: \u0e15\u0e31\u0e14 key \u0e17\u0e35\u0e48\u0e2d\u0e49\u0e32\u0e07\u0e04\u0e2d\u0e25\u0e31\u0e21\u0e19\u0e4c\u0e17\u0e35\u0e48\u0e16\u0e39\u0e01\u0e25\u0e1a",
    "                    'z_volatility_3m': current_vol, 'z_velocity': get_lag(1) - get_lag(3),\n"
    "                    'news_relevance_count': curr_df['news_relevance_count'].iloc[-1], 'news_momentum': 0,\n",
    "                    'z_volatility_3m': current_vol, 'z_velocity': get_lag(1) - get_lag(3),\n",
)

# ── D. ตัดการสร้างฟีเจอร์ใน create_features ────────────────────────────────
rep(
    "D. create_features: \u0e15\u0e31\u0e14\u0e01\u0e32\u0e23\u0e2a\u0e23\u0e49\u0e32\u0e07 news_momentum",
    "        for col in ['news_relevance_count', 'new_product_mentions']:\n"
    "            if col not in df.columns: df[col] = 0\n"
    "            df[col] = df[col].fillna(0)\n"
    "        df['news_momentum'] = df.groupby(group_col)['news_relevance_count'].transform(lambda x: x.ffill().diff().fillna(0))\n"
    "        return df.fillna(0)",
    "        # Phase 0 (2026-08-28): \u0e15\u0e31\u0e14\u0e01\u0e32\u0e23\u0e2a\u0e23\u0e49\u0e32\u0e07 news_relevance_count/news_momentum \u0e2d\u0e2d\u0e01 (\u0e1f\u0e35\u0e40\u0e08\u0e2d\u0e23\u0e4c\u0e15\u0e32\u0e22 0.0%)\n"
    "        # 'new_product_mentions' \u0e16\u0e39\u0e01\u0e15\u0e31\u0e14\u0e44\u0e1b\u0e1e\u0e23\u0e49\u0e2d\u0e21\u0e01\u0e31\u0e19\u0e40\u0e1e\u0e23\u0e32\u0e30\u0e44\u0e21\u0e48\u0e40\u0e04\u0e22\u0e16\u0e39\u0e01\u0e40\u0e0b\u0e47\u0e15\u0e04\u0e48\u0e32\u0e08\u0e32\u0e01\u0e17\u0e35\u0e48\u0e44\u0e2b\u0e19\u0e40\u0e25\u0e22 \u0e41\u0e25\u0e30\u0e44\u0e21\u0e48\u0e40\u0e04\u0e22\u0e2d\u0e22\u0e39\u0e48\u0e43\u0e19\n"
    "        # feature_cols - \u0e40\u0e1b\u0e47\u0e19\u0e42\u0e04\u0e49\u0e14\u0e15\u0e32\u0e22\u0e17\u0e35\u0e48\u0e2b\u0e25\u0e07\u0e40\u0e2b\u0e25\u0e37\u0e2d\u0e21\u0e32 (verify \u0e14\u0e49\u0e27\u0e22 grep \u0e41\u0e25\u0e49\u0e27\u0e27\u0e48\u0e32\u0e2d\u0e49\u0e32\u0e07\u0e16\u0e36\u0e07\u0e41\u0e04\u0e48\u0e1a\u0e23\u0e23\u0e17\u0e31\u0e14\u0e19\u0e35\u0e49\u0e08\u0e38\u0e14\u0e40\u0e14\u0e35\u0e22\u0e27)\n"
    "        return df.fillna(0)",
)

# ── E. ตัดบล็อกยิงข่าว+LLM ทิ้งทั้งก้อน ─────────────────────────────────────
E_OLD = (
    "    # --- 3. NEWS PROCESSING (Fetch by cluster, \u0e17\u0e33\u0e41\u0e1a\u0e1a\u0e02\u0e19\u0e32\u0e19\u0e40\u0e1e\u0e23\u0e32\u0e30\u0e41\u0e15\u0e48\u0e25\u0e30\u0e04\u0e39\u0e48 cluster x \u0e40\u0e14\u0e37\u0e2d\u0e19\n"
)
i_start = s.index(E_OLD)
i_end = s.index("    df_keyword_trim['z_score']", i_start)
E_NEW = (
    "    # --- 3. (\u0e27\u0e48\u0e32\u0e07) \u0e40\u0e14\u0e34\u0e21\u0e40\u0e1b\u0e47\u0e19\u0e1a\u0e25\u0e47\u0e2d\u0e01 NEWS PROCESSING \u0e17\u0e35\u0e48\u0e22\u0e34\u0e07 Google News + LLM \u0e2b\u0e25\u0e32\u0e22\u0e23\u0e49\u0e2d\u0e22\u0e04\u0e23\u0e31\u0e49\u0e07\u0e15\u0e48\u0e2d\u0e23\u0e2d\u0e1a\n"
    "    #     (1 \u0e04\u0e23\u0e31\u0e49\u0e07\u0e15\u0e48\u0e2d\u0e17\u0e38\u0e01\u0e04\u0e39\u0e48 \u0e04\u0e25\u0e31\u0e2a\u0e40\u0e15\u0e2d\u0e23\u0e4c x \u0e40\u0e14\u0e37\u0e2d\u0e19) \u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e2a\u0e23\u0e49\u0e32\u0e07\u0e1f\u0e35\u0e40\u0e08\u0e2d\u0e23\u0e4c news_relevance_count\n"
    "    #     \u0e15\u0e31\u0e14\u0e17\u0e34\u0e49\u0e07\u0e17\u0e31\u0e49\u0e07\u0e01\u0e49\u0e2d\u0e19\u0e43\u0e19 Phase 0 (2026-08-28) \u0e40\u0e1e\u0e23\u0e32\u0e30 feature importance = 0.0000 \u0e40\u0e1b\u0e4a\u0e30\u0e17\u0e38\u0e01 cutoff\n"
    "    #     \u0e17\u0e31\u0e49\u0e07 RandomForest \u0e41\u0e25\u0e30 XGBoost - \u0e08\u0e48\u0e32\u0e22\u0e41\u0e1e\u0e07\u0e17\u0e35\u0e48\u0e2a\u0e38\u0e14\u0e41\u0e15\u0e48\u0e42\u0e21\u0e40\u0e14\u0e25\u0e44\u0e21\u0e48\u0e44\u0e14\u0e49\u0e43\u0e0a\u0e49\u0e40\u0e25\u0e22\u0e41\u0e21\u0e49\u0e41\u0e15\u0e48\u0e19\u0e34\u0e14\u0e40\u0e14\u0e35\u0e22\u0e27\n"
    "    #     \u0e15\u0e49\u0e19\u0e15\u0e2d\u0e17\u0e35\u0e48\u0e19\u0e48\u0e32\u0e08\u0e30\u0e17\u0e33\u0e43\u0e2b\u0e49\u0e1f\u0e35\u0e40\u0e08\u0e2d\u0e23\u0e4c\u0e15\u0e32\u0e22: \u0e04\u0e49\u0e19\u0e02\u0e48\u0e32\u0e27\u0e14\u0e49\u0e27\u0e22 \"\u0e0a\u0e37\u0e48\u0e2d\u0e04\u0e25\u0e31\u0e2a\u0e40\u0e15\u0e2d\u0e23\u0e4c\" \u0e17\u0e35\u0e48\u0e22\u0e32\u0e27\u0e41\u0e25\u0e30\u0e40\u0e1b\u0e47\u0e19\u0e20\u0e32\u0e29\u0e32\u0e01\u0e32\u0e23\u0e15\u0e25\u0e32\u0e14\n"
    "    #     \u0e22\u0e49\u0e2d\u0e19\u0e2b\u0e25\u0e31\u0e07\u0e44\u0e1b\u0e16\u0e36\u0e07\u0e1b\u0e35 2004 \u0e0b\u0e36\u0e48\u0e07\u0e41\u0e17\u0e1a\u0e44\u0e21\u0e48\u0e21\u0e35\u0e02\u0e48\u0e32\u0e27\u0e15\u0e23\u0e07\u0e40\u0e25\u0e22 \u0e04\u0e48\u0e32\u0e08\u0e36\u0e07\u0e40\u0e1b\u0e47\u0e19 0 \u0e40\u0e01\u0e37\u0e2d\u0e1a\u0e17\u0e31\u0e49\u0e07\u0e15\u0e32\u0e23\u0e32\u0e07\n"
    "\n"
    "    # --- 4. FEATURE GEN & MODELING (AT COMPOSITE LEVEL) ---\n"
)
s = s[:i_start] + E_NEW + s[i_end:]
edits.append("E. \u0e15\u0e31\u0e14\u0e1a\u0e25\u0e47\u0e2d\u0e01 NEWS PROCESSING \u0e17\u0e31\u0e49\u0e07\u0e01\u0e49\u0e2d\u0e19")

# ── F. ตัดฟังก์ชันที่ตายตาม ────────────────────────────────────────────────
i_f = s.index("    def filter_relevant_news_llm(news_results, cluster_name):")
i_f_end = s.index("    def get_month_bounds(date_obj):", i_f)
s = s[:i_f] + (
    "    # Phase 0 (2026-08-28): \u0e15\u0e31\u0e14 filter_relevant_news_llm() + search_news() \u0e2d\u0e2d\u0e01\n"
    "    # \u0e17\u0e31\u0e49\u0e07\u0e04\u0e39\u0e48\u0e16\u0e39\u0e01\u0e40\u0e23\u0e35\u0e22\u0e01\u0e08\u0e32\u0e01\u0e1a\u0e25\u0e47\u0e2d\u0e01 NEWS PROCESSING \u0e17\u0e35\u0e48\u0e16\u0e39\u0e01\u0e15\u0e31\u0e14\u0e44\u0e1b\u0e40\u0e17\u0e48\u0e32\u0e19\u0e31\u0e49\u0e19 \u0e08\u0e36\u0e07\u0e01\u0e25\u0e32\u0e22\u0e40\u0e1b\u0e47\u0e19\u0e42\u0e04\u0e49\u0e14\u0e15\u0e32\u0e22\u0e17\u0e31\u0e19\u0e17\u0e35\n"
    "    # (verify \u0e14\u0e49\u0e27\u0e22 grep \u0e41\u0e25\u0e49\u0e27\u0e27\u0e48\u0e32\u0e44\u0e21\u0e48\u0e21\u0e35\u0e17\u0e35\u0e48\u0e2d\u0e37\u0e48\u0e19\u0e40\u0e23\u0e35\u0e22\u0e01\u0e43\u0e0a\u0e49)\n"
    "\n"
) + s[i_f_end:]
edits.append("F. \u0e15\u0e31\u0e14 filter_relevant_news_llm + search_news")

io.open(P, "w", encoding="utf-8").write(s)

print("\u0e41\u0e01\u0e49\u0e2a\u0e33\u0e40\u0e23\u0e47\u0e08 %d \u0e08\u0e38\u0e14:" % len(edits))
for e in edits:
    print("  -", e)
print()
print("\u0e1a\u0e23\u0e23\u0e17\u0e31\u0e14: %d -> %d (\u0e25\u0e14 %d)" % (
    orig.count("\n") + 1, s.count("\n") + 1, orig.count("\n") - s.count("\n")))
